### 문제등록
POST localhost:8080/api/problems
Content-Type: application/json

{
  "title": "where is koreanCow1",
  "content": "koreanCow is delicious",
  "limitFactor": "Never eat dog",
  "limitTime": 60,
  "difficulty": 1,
  "baseCodes" : [{
    "language": "PYTHON",
    "code": "x=1; y=\"hello world!\"; figure;plot(x,y);"
  },{
    "language": "JAVA",
    "code": "public class Main{public static void main(String[] args){System.out.println(\"Hello World!\");}}"
  }
  ]
}

### 문제조회
GET localhost:8080/api/problems
Content-Type: application/json

{
}