### 회원가입
POST localhost:8080/api/signup
Content-Type: application/json

{
  "nickname": "짱우혁짱아님2",
  "username": "KoreanCow1",
  "password": "1q2w3e4r"
}

### 회원정보수정
PATCH localhost:8080/api/users/1
Content-Type: application/json

{
  "nickname": "zeno"
}

### 회원정보 조회
GET localhost:8080/api/users/1
Content-Type: application/json